FROM python:3.7

# MAINTAINER superman for hzj

LABEL version="0.1v"

WORKDIR /root/code

COPY ./BA ./
# 这里copy的只是BA这个项目下面的内容，并不是BA这个文件夹

RUN pip install -r requirements.txt

# EXPOSE 8887

# CMD ['uvicorn','main:app',"--host" ,"0.0.0.0","--reload"]

# 上面的dockerfile会报错，因为用了单引号。。。
CMD ["uvicorn","main:app","--host" ,"0.0.0.0","--reload"]


# 启动容器
# docker run -itd -p 8887:8887 -t v2